# Project-wide Gradle settings.

org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2,TLSv1.3

systemProp.https.protocols=TLSv1.2,TLSv1.3

android.useAndroidX=true

# 🔥 IMPORTANT (KEEP THIS)
reactNativeArchitectures=armeabi-v7a,arm64-v8a


# Hermes engine
hermesEnabled=true

# Edge to edge
edgeToEdgeEnabled=false

# VisionCamera fix
VisionCamera_enableFrameProcessors=true